/**
 * Stable identity for commands committed by a game Durable Object.
 *
 * The document shape, its canonicalization and the principal spellings live in
 * `../command-request.js`, shared with the create reservation D1 holds for a
 * game that has no object yet. This module is the game-command half: which
 * operation name a command carries, and which parts of it were the caller's
 * choice.
 */

import { botPrincipal, CommandIdentityError, canonicalRequest, userPrincipal } from "../command-request.js";
import type { Command, Principal } from "../protocol.js";

export { CommandIdentityError };

export interface CommandIdentity {
  /** `user:<id>` or `bot:<id>`: the only scope the stored result is replayable
   * to, so two principals may independently choose the same command id. */
  principalId: string;
  commandId: string;
  /** Canonical RFC 8785 JSON of the command's semantic intent. */
  request: string;
}

/**
 * The principal a receipt is scoped to, or null for an identity-less system
 * command.
 *
 * A system command (a deadline timeout) is generated by the engine from
 * committed state, never submitted, so no caller owns an id for it and nothing
 * can retry it ambiguously. Those commands are idempotent because the kernel
 * abstains once the state they were derived from has moved on, which is a
 * stronger guarantee than a receipt: it holds across a lost alarm, a replaced
 * object and a redeployment. Giving them receipts would store a permanent row
 * per turn to duplicate a check the kernel already performs.
 *
 * @throws {CommandIdentityError} if an actor carries neither or both ids.
 */
export function commandPrincipal(actor: Principal | null): string | null {
  if (actor === null) return null;
  if (actor.userId !== null && actor.botId === null) return userPrincipal(actor.userId);
  if (actor.botId !== null && actor.userId === null) return botPrincipal(actor.botId);
  throw new CommandIdentityError("a command principal must carry exactly one immutable id");
}

/** The stable operation name in the canonical document; see
 * {@link RequestDocument.operation}. */
function operation(cmd: Command): string {
  switch (cmd.kind) {
    case "join":
      return "game.join";
    case "leave":
      return "game.leave";
    case "cancel":
      return "game.cancel";
    case "start":
      return "game.start";
    case "add-bot":
      return "game.add-bot";
    case "action":
      return "game.action";
    case "lifecycle":
      switch (cmd.type) {
        case "forfeit":
          return "game.forfeit";
        case "autoForfeit":
          return "game.auto-forfeit";
        case "timeout":
          return "game.timeout";
      }
  }
}

/** Only what the caller chose; see {@link RequestDocument.payload}. */
function payload(cmd: Command, actionData: unknown): unknown {
  switch (cmd.kind) {
    case "join":
    case "leave":
    case "cancel":
    case "start":
      return {};
    case "add-bot":
      return { botId: cmd.botId };
    case "action":
      return { seat: cmd.seat, expectedVersion: cmd.expectedVersion, data: actionData };
    case "lifecycle":
      return cmd.type === "timeout" ? {} : { seat: cmd.seat };
  }
}

/**
 * Build the identity a receipt is stored under and compared by.
 *
 * `resource` is the game the OWNING OBJECT is authoritative for, passed in from
 * `meta`, never the id the caller asked for. A receipt can then never name a
 * game its own Durable Object does not own, whatever routing did.
 *
 * Returns null for an identity-less system command; see {@link commandPrincipal}.
 */
export function commandIdentity(cmd: Command, resource: string, actionData: unknown): CommandIdentity | null {
  const principalId = commandPrincipal(cmd.actor);
  if (principalId === null) return null;
  return {
    principalId,
    commandId: cmd.commandId,
    request: canonicalRequest({ principal: principalId, operation: operation(cmd), resource, payload: payload(cmd, actionData) }),
  };
}
