/**
 * Stable identity for commands committed by a game Durable Object.
 *
 * A receipt answers one question: has THIS principal already committed THIS
 * command id, and did they mean the same thing by it? So identity is a pair of
 * values, both derived here:
 *
 * - `principalId`, the immutable actor the stored result may be replayed to;
 * - `request`, the canonical JSON of the command's semantic intent.
 *
 * `request` is stored and compared verbatim rather than hashed. A digest would
 * save bytes next to a receipt that already stores a whole session snapshot,
 * and it would cost an `await crypto.subtle.digest` in the middle of the
 * Durable Object's read-then-write critical section. An exact string comparison
 * is synchronous, has no collision case to reason about, and says what it means.
 *
 * Canonicalization is RFC 8785 (JCS) via that RFC's own reference JavaScript
 * implementation, so key order, number formatting and Unicode escaping are the
 * spec's problem and not ours. It also throws on NaN and Infinity, which is the
 * I-JSON validation we would otherwise hand-roll.
 */

import canonicalize from "canonicalize";

import type { Command, Principal } from "../protocol.js";

/** Bumped only if the document shape below changes. An old receipt then reads
 * as a different intent, which is the safe direction: a conflict, never a
 * wrongly replayed result. */
const REQUEST_VERSION = 1;

export interface CommandIdentity {
  /** `user:<id>` or `bot:<id>`: the only scope the stored result is replayable
   * to, so two principals may independently choose the same command id. */
  principalId: string;
  commandId: string;
  /** Canonical RFC 8785 JSON of the command's semantic intent. */
  request: string;
}

/** A command whose payload is outside the JSON data model RFC 8785 accepts. */
export class CommandIdentityError extends TypeError {}

/**
 * The principal a receipt is scoped to, or null for an identity-less system
 * command.
 *
 * A system command (a deadline timeout) is generated by the engine from
 * committed state, never submitted, so no caller owns an id for it and nothing
 * can retry it ambiguously. Those commands are idempotent because the kernel
 * abstains once the state they were derived from has moved on, which is a
 * stronger guarantee than a receipt: it holds across a lost alarm, a replaced
 * object and a redeployment. Giving them receipts would store a permanent row
 * per turn to duplicate a check the kernel already performs.
 */
export function commandPrincipal(actor: Principal | null): string | null {
  if (actor === null) return null;
  if (actor.userId !== null && actor.botId === null) return `user:${actor.userId}`;
  if (actor.botId !== null && actor.userId === null) return `bot:${actor.botId}`;
  throw new CommandIdentityError("a command principal must carry exactly one immutable id");
}

/** The stable operation name in the canonical document. Reusing one id across
 * two operations must read as a conflict, so these names are part of the
 * contract and may not be derived from a changeable enum. */
function operation(cmd: Command): string {
  switch (cmd.kind) {
    case "join":
      return "game.join";
    case "leave":
      return "game.leave";
    case "cancel":
      return "game.cancel";
    case "start":
      return "game.start";
    case "add-bot":
      return "game.add-bot";
    case "action":
      return "game.action";
    case "lifecycle":
      switch (cmd.type) {
        case "forfeit":
          return "game.forfeit";
        case "autoForfeit":
          return "game.auto-forfeit";
        case "timeout":
          return "game.timeout";
      }
  }
}

/** Only what the caller chose. Host-generated values (arrival time, RNG seed,
 * request metadata) are excluded, or an honest retry would never match. */
function payload(cmd: Command, actionData: unknown): unknown {
  switch (cmd.kind) {
    case "join":
    case "leave":
    case "cancel":
    case "start":
      return {};
    case "add-bot":
      return { botId: cmd.botId };
    case "action":
      return { seat: cmd.seat, expectedVersion: cmd.expectedVersion, data: actionData };
    case "lifecycle":
      return cmd.type === "timeout" ? {} : { seat: cmd.seat };
  }
}

/**
 * Build the identity a receipt is stored under and compared by.
 *
 * `resource` is the game the OWNING OBJECT is authoritative for, passed in from
 * `meta`, never the id the caller asked for. A receipt can then never name a
 * game its own Durable Object does not own, whatever routing did.
 *
 * Returns null for an identity-less system command; see {@link commandPrincipal}.
 */
export function commandIdentity(cmd: Command, resource: string, actionData: unknown): CommandIdentity | null {
  const principalId = commandPrincipal(cmd.actor);
  if (principalId === null) return null;
  const document = { version: REQUEST_VERSION, principal: principalId, operation: operation(cmd), resource, payload: payload(cmd, actionData) };
  let request: string | undefined;
  try {
    request = canonicalize(document);
  } catch (error) {
    throw new CommandIdentityError(`command payload is not canonicalizable JSON: ${error instanceof Error ? error.message : String(error)}`);
  }
  if (request === undefined) throw new CommandIdentityError("command payload canonicalized to nothing");
  return { principalId, commandId: cmd.commandId, request };
}
