/**
 * The query parameters shared across the paged reads, and the one rule that
 * shapes all of them: **a query parameter is parsed, never coerced**.
 *
 * That rule is here because breaking it cost every paged list in the product.
 * `z.coerce.number()` is `Number()`, and `Number()` maps both `""` and `null`
 * to `0`. Following that through four layers, each behaving correctly:
 *
 * 1. `z.coerce.number().int().min(0)` genuinely *accepts* `null` and yields
 *    `0`, so the emitted OpenAPI schema truthfully says `["integer", "null"]`.
 *    (With `.min(1)` it does not, which is why some parameters were affected
 *    and others were not - the difference looked like nothing at all.)
 * 2. `openapi-generator` reads that nullability and correctly *omits* its
 *    `if (x != null)` guard, because the API has declared that null is a value
 *    it accepts.
 * 3. dio renders the resulting null query value as a bare `?to=`.
 * 4. The server coerces `""` straight back to `0`.
 *
 * Nothing in that chain is a bug in anyone's library. The whole failure is
 * generated by asking `Number()` to be a parser. A cursor of `0` meant "older
 * than anything that has ever happened", so the lobby, both `games/mine`
 * buckets, the friends list and every history screen returned `200` with an
 * empty array, and a `to` of `0` clamped replays to a single frame.
 *
 * Parsing instead of coercing fixes it at the origin and in both directions:
 * the schema no longer accepts null, so the generated client omits the
 * parameter on its own and the bad request is never built; and an empty or
 * malformed value that arrives anyway is a loud `400` rather than a silent
 * zero. Nothing downstream has to compensate, which is why there is no
 * request-rewriting middleware in this codebase.
 *
 * They live in one module rather than beside their routes because the
 * duplication was real and had already drifted: `reads.ts` declared a `limit`
 * and a `cursor`, and `social.ts` carried an inline copy of both that any fix
 * to the originals would have missed.
 */

import { z } from "@hono/zod-openapi";

/**
 * A non-negative integer arriving as a string, parsed strictly.
 *
 * The regex is the parser, and it is deliberately narrow: `Number()` also
 * accepts `"1e3"` as 1000, `"0x10"` as 16, `" 5"` as 5 and `"1.0"` as 1, none
 * of which any caller means to send and all of which it would silently honour.
 *
 * `.openapi()` restates the bounds because the runtime schema and the published
 * one legitimately differ here: the wire carries an integer, and what arrives at
 * the process boundary is the string spelling of one. Both are derived from the
 * same two arguments, so they cannot drift apart.
 */
function intQuery(min: number, max: number) {
  return z.string().regex(/^\d+$/, "must be a non-negative integer").transform(Number).pipe(z.number().int().min(min).max(max)).openapi({ type: "integer", minimum: min, maximum: max });
}

/** Page size. Bounded because it feeds `LIMIT` and, on the batch reads, an
 * `IN (...)` list; unbounded, one request could ask D1 for everything. */
export const limitQuery = intQuery(1, 50).default(20).openapi({ type: "integer", minimum: 1, maximum: 50, default: 20 });

/** A frame version: the bounds of a replay range. Zero is a legitimate value a
 * caller can mean, which under coercion was indistinguishable from having sent
 * nothing at all. */
export const versionQuery = intQuery(0, Number.MAX_SAFE_INTEGER);

/**
 * Keyset cursor: the opaque `nextCursor` from the previous page, echoed back.
 * Absent on the first page.
 *
 * A string with no coercion and no structure declared, because a client is not
 * meant to build one - only to hand back what it was given. `cursor.ts` covers
 * what is inside and why it is not a number. `min(1)` so that an empty cursor
 * is refused by the schema rather than reaching the decoder as a mystery.
 */
export const cursorQuery = z.string().min(1).optional();

/** The continuation token for the next page, or null when the list is
 * exhausted. Null is an answer, not a hint: see `Page` in `cursor.ts`. */
export const nextCursorShape = z.string().nullable().openapi({ description: "Pass as `cursor` to fetch the next page. Null when there are no more results." });
