/**
 * The D1 schema — the global store: identity, social,
 * bots, ratings, and game summary rows. A read-model + registry, never an
 * arbiter: live game truth is each game's DO; D1 is what lists, lobbies,
 * leaderboards, and profiles read. Never wake a DO to serve a read.
 *
 * Ports the Supabase-era tables with the decided simplifications: `users` and
 * `user_profiles` merged; `game_outcomes` folded into the games row as JSON;
 * no identity denormalization onto games (the batch `players?ids=` endpoint +
 * the client's persisted cache covers it). Firebase uids are TEXT keys;
 * engine-generated ids are UUID strings; instants are epoch milliseconds.
 *
 * Migrations are generated by drizzle-kit and applied with
 * `wrangler d1 migrations apply` — never at runtime.
 */

import type { GameStatus, Seat } from "@eigen/kernel";
import type { GameAccess, JsonObject, OutcomeEntry } from "@eigen/rules";
import { sql } from "drizzle-orm";
import { check, index, integer, real, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

/** Merged users + user_profiles (the split served RLS separation that no
 * longer exists). Provisioned on first sight of a verified Firebase token;
 * `avatar_url` defaults to the provider photo (null ⇒ client renders
 * initials). */
export const users = sqliteTable(
  "users",
  {
    /** The Firebase uid — stable across guest → permanent upgrades. */
    id: text("id").primaryKey(),
    username: text("username").notNull().unique(),
    /** Null for guests until they convert; UNIQUE tolerates multiple NULLs. */
    email: text("email").unique(),
    displayName: text("display_name").notNull(),
    avatarUrl: text("avatar_url"),
    isAnonymous: integer("is_anonymous", { mode: "boolean" }).notNull(),
    createdAt: integer("created_at").notNull(),
    updatedAt: integer("updated_at").notNull(),
  },
  (t) => [index("idx_users_username").on(t.username)],
);

/** The game summary/read-model row (created worker-direct, before the
 * DO exists;: updated post-commit from DO effects, accepted staleness). */
export const games = sqliteTable(
  "games",
  {
    id: text("id").primaryKey(),
    createdBy: text("created_by"),
    status: text("status").$type<GameStatus>().notNull(),
    access: text("access").$type<GameAccess>().notNull(),
    schemaVersion: integer("schema_version").notNull(),
    config: text("config", { mode: "json" }).$type<JsonObject>().notNull(),
    /** Exactly one timing mode: turn XOR budget XOR untimed (worker policy
     * validates; no CHECK — D1 is display, the DO is integrity). */
    turnSeconds: integer("turn_seconds"),
    budgetSeconds: integer("budget_seconds"),
    incrementSeconds: integer("increment_seconds"),
    rated: integer("rated", { mode: "boolean" }).notNull(),
    ratingPool: text("rating_pool"),
    minPlayers: integer("min_players").notNull(),
    maxPlayers: integer("max_players").notNull(),
    shortCode: text("short_code").notNull().unique(),
    /** Dashboard hints ("your turn", countdowns) — display-only staleness OK. */
    pendingPlayers: text("pending_players", { mode: "json" }).$type<number[] | null>(),
    turnDeadline: integer("turn_deadline"),
    /** Folded former game_outcomes table — written once by the finish apply. */
    outcomes: text("outcomes", { mode: "json" }).$type<OutcomeEntry[] | null>(),
    /**: the D1 apply's idempotency key; set when the apply lands. */
    finishId: text("finish_id"),
    /** Stamped by the finish apply (and the future abort path) — history
     * lists sort by it, as the Supabase era did. */
    finishedAt: integer("finished_at"),
    /** seam: NULL = history lives in the game's DO. V1 never writes or
     * reads it; the future cold-tier sweep starts stamping it. */
    archivedAt: integer("archived_at"),
    createdAt: integer("created_at").notNull(),
    updatedAt: integer("updated_at").notNull(),
  },
  (t) => [
    index("idx_games_status_access").on(t.status, t.access),
    index("idx_games_created_by").on(t.createdBy),
    // The lobby page: public joinable games, newest first (ported partial index).
    index("idx_games_lobby").on(t.createdAt).where(sql`access = 'public' AND status IN ('waiting', 'ready')`),
  ],
);

/** The roster join table — one row per seat, the indexed access path for
 * "games of user X" (ported from the Supabase era; the JSON-snapshot detour
 * was reverted 2026-07-17). Written at create/join/leave alongside the games
 * row; the DO's own roster remains the integrity copy. The game-scoped
 * unique indexes guard the join race exactly as the old schema did. */
export const participants = sqliteTable(
  "participants",
  {
    id: text("id").primaryKey(),
    gameId: text("game_id").notNull(),
    /** Exactly one of user_id/bot_id for a live identity; both may be NULL
     * after an account purge (worker-enforced — D1 carries no CHECKs). */
    userId: text("user_id"),
    botId: text("bot_id"),
    playerIndex: integer("player_index").notNull(),
    type: text("type").$type<Seat["type"]>().notNull(),
    createdAt: integer("created_at").notNull(),
  },
  (t) => [uniqueIndex("idx_participants_unique").on(t.gameId, t.userId).where(sql`user_id IS NOT NULL`), uniqueIndex("idx_participants_player_index").on(t.gameId, t.playerIndex), index("idx_participants_user_id").on(t.userId), index("idx_participants_game_id").on(t.gameId)],
);

/** Friends — canonical pair order (`user_id_1 < user_id_2`, worker-enforced)
 * + UNIQUE, as the Supabase era had. */
export const relationships = sqliteTable(
  "relationships",
  {
    id: text("id").primaryKey(),
    userId1: text("user_id_1").notNull(),
    userId2: text("user_id_2").notNull(),
    initiatedBy: text("initiated_by").notNull(),
    /** `blocked` is declared for Dart-twin parity (the old enum had it);
     * no engine logic acts on it yet — the social routes milestone decides. */
    status: text("status").$type<"pending" | "accepted" | "blocked">().notNull(),
    createdAt: integer("created_at").notNull(),
    updatedAt: integer("updated_at").notNull(),
  },
  (t) => [uniqueIndex("idx_relationships_pair").on(t.userId1, t.userId2), index("idx_relationships_user2").on(t.userId2)],
);

/** How a bot's moves are produced — the dispatch discriminator:
 * - `engine`: the brain ships in the game's `GameModule` as
 *   `GameRules.botActions[username]`, run in-process by the DO;
 * - `external`: the bot is hosted elsewhere and woken over HMAC (`webhook_url`
 *   is then required);
 * - `local`: client-driven (future offline-solo transcript import) — a
 *   registry row for identity only, never dispatched server-side.
 * Replaces the Supabase-era `is_local` boolean. */
export type BotType = "engine" | "external" | "local";

/** Bot registry. `type` selects the dispatch path; `webhook_url` is
 * required for (and only for) `external`. `username` is the stable,
 * human-readable key the game's `botActions` map is keyed by for `engine`
 * bots. */
export const bots = sqliteTable(
  "bots",
  {
    id: text("id").primaryKey(),
    username: text("username").notNull().unique(),
    displayName: text("display_name").notNull(),
    avatarUrl: text("avatar_url"),
    /** Highest game schema this bot supports — the seating gate. */
    schemaVersion: integer("schema_version").notNull(),
    type: text("type").$type<BotType>().notNull(),
    webhookUrl: text("webhook_url"),
    ratedEligible: integer("rated_eligible", { mode: "boolean" }).notNull(),
    config: text("config", { mode: "json" }).$type<JsonObject>().notNull(),
    createdAt: integer("created_at").notNull(),
  },
  (t) => [
    // A webhook is present iff the bot is external — the type/columns stay a
    // valid discriminated union at the storage layer, not just in TS.
    check("bots_webhook_matches_type", sql`(${t.type} = 'external') = (${t.webhookUrl} IS NOT NULL)`),
    check("bots_type_valid", sql`${t.type} IN ('engine', 'external', 'local')`),
  ],
);

/** Per-identity per-pool OpenSkill rating. Exactly one of user_id/bot_id is
 * set. `revision` is the CAS counter: the finish apply reads
 * (mu, sigma, revision), computes in TS, updates WHERE revision matches, and
 * recomputes on conflict — the fix for the legacy concurrent-finish
 * lost-update bug. */
export const playerRatings = sqliteTable(
  "player_ratings",
  {
    id: text("id").primaryKey(),
    userId: text("user_id"),
    botId: text("bot_id"),
    pool: text("pool").notNull(),
    mu: real("mu").notNull(),
    sigma: real("sigma").notNull(),
    /** max(0, round((mu − 3σ) · 40)) — denormalized for leaderboards. */
    displayRating: integer("display_rating").notNull(),
    revision: integer("revision").notNull(),
    createdAt: integer("created_at").notNull(),
    updatedAt: integer("updated_at").notNull(),
  },
  (t) => [uniqueIndex("idx_player_ratings_user_pool").on(t.userId, t.pool).where(sql`user_id IS NOT NULL`), uniqueIndex("idx_player_ratings_bot_pool").on(t.botId, t.pool).where(sql`bot_id IS NOT NULL`)],
);

/** Immutable per-game rating log for the profile history screen. Unique per
 * (game, identity) and carrying finish_id, so a re-poked apply is a no-op. */
export const ratingHistory = sqliteTable(
  "rating_history",
  {
    id: text("id").primaryKey(),
    userId: text("user_id"),
    botId: text("bot_id"),
    gameId: text("game_id").notNull(),
    pool: text("pool").notNull(),
    finishId: text("finish_id").notNull(),
    muBefore: real("mu_before").notNull(),
    sigmaBefore: real("sigma_before").notNull(),
    displayBefore: integer("display_before").notNull(),
    muAfter: real("mu_after").notNull(),
    sigmaAfter: real("sigma_after").notNull(),
    displayAfter: integer("display_after").notNull(),
    displayChange: integer("display_change").notNull(),
    createdAt: integer("created_at").notNull(),
  },
  (t) => [uniqueIndex("idx_rating_history_game_user").on(t.gameId, t.userId).where(sql`user_id IS NOT NULL`), uniqueIndex("idx_rating_history_game_bot").on(t.gameId, t.botId).where(sql`bot_id IS NOT NULL`), index("idx_rating_history_user_pool").on(t.userId, t.pool, t.createdAt)],
);

/** FCM push targets, keyed by Firebase Installation ID — unchanged. */
export const deviceInstallations = sqliteTable(
  "device_installations",
  {
    fid: text("fid").primaryKey(),
    userId: text("user_id").notNull(),
    platform: text("platform").$type<"ios" | "android" | "web">().notNull(),
    updatedAt: integer("updated_at").notNull(),
  },
  (t) => [index("idx_device_installations_user").on(t.userId)],
);
