{{flutter_js}}
{{flutter_build_config}}

// Flutter starts at once. Neither worker below is anything this page waits on,
// so they register beside it rather than ahead of it.
_flutter.loader.load();

if ("serviceWorker" in navigator) {
  // The app's own worker, generated by Workbox (workbox-config.cjs): the
  // precached build, which is what lets the app open with no network.
  navigator.serviceWorker.register("sw.js").catch((error) => {
    console.warn("App service worker registration failed", error);
  });
  // Firebase Messaging's worker, which owns only its push scope.
  navigator.serviceWorker.register("firebase-messaging-sw.js", { scope: "/firebase-cloud-messaging-push-scope" }).catch((error) => {
    console.warn("Firebase Messaging service worker registration failed", error);
  });
}

// CanvasKit and the Firebase JS SDK load from Google's CDN, which the app's
// worker caches as they pass through it. A first visit fetches them before that
// worker controls the page, so the page copies what it loaded into the same
// cache ("eigen-cdn" in workbox-config.cjs), and drops versions of each it no
// longer loads. Without this, the first visit would not open offline.
if ("caches" in self && "PerformanceObserver" in self) {
  const cdn = /^https:\/\/www\.gstatic\.com\/(flutter-canvaskit|firebasejs)\/[^/]+\//;
  new PerformanceObserver(async (entries) => {
    for (const { name } of entries.getEntries()) {
      const loaded = cdn.exec(name);
      if (!loaded) continue;
      try {
        const cache = await caches.open("eigen-cdn");
        if (!(await cache.match(name))) await cache.add(name);
        for (const request of await cache.keys()) {
          const cached = cdn.exec(request.url);
          if (cached && cached[1] === loaded[1] && cached[0] !== loaded[0]) await cache.delete(request);
        }
      } catch {
        // Only a later offline start is at stake, and the next load tries again.
      }
    }
  }).observe({ type: "resource", buffered: true });
}
