import Link from "@docusaurus/Link";
import { type Game, games } from "@site/src/data/games";
import Heading from "@theme/Heading";
import Layout from "@theme/Layout";
import type { ReactNode } from "react";
import styles from "./showcase.module.css";

function GameCard({ game }: { game: Game }): ReactNode {
  return (
    <div className={styles.card}>
      <div className={styles.cardHeader}>
        <span className={styles.emoji} aria-hidden="true">
          {game.emoji}
        </span>
        <div>
          <Heading as="h3" className={styles.cardTitle}>
            {game.name}
          </Heading>
          <p className={styles.tagline}>{game.tagline}</p>
        </div>
      </div>
      <p className={styles.description}>{game.description}</p>
      <div className={styles.links}>
        {game.site && (
          <Link className="button button--primary button--sm" to={game.site}>
            Website
          </Link>
        )}
        {game.android && (
          <Link className="button button--secondary button--sm" to={game.android}>
            Google Play
          </Link>
        )}
        {game.ios && (
          <Link className="button button--secondary button--sm" to={game.ios}>
            App Store
          </Link>
        )}
        {game.source && (
          <Link className="button button--secondary button--sm" to={game.source}>
            Source
          </Link>
        )}
      </div>
    </div>
  );
}

export default function Showcase(): ReactNode {
  return (
    <Layout title="Showcase" description="Games built on the EigenInteractive engine.">
      <main className="container margin-vert--lg">
        <Heading as="h1">Showcase</Heading>
        <p className={styles.intro}>Games built on EigenInteractive. Each one is a single Cloudflare Worker that owns its own domain, database and players — and each ships its own website, generated by the engine.</p>
        <div className={styles.grid}>
          {games.map((game) => (
            <GameCard game={game} key={game.name} />
          ))}
        </div>
        <p className={styles.outro}>
          Building one? <Link to="/docs/getting-started/quickstart">Start here</Link>.
        </p>
      </main>
    </Layout>
  );
}
