// The web app's service worker, generated by Workbox from the Flutter build
// (decision 0014). `build:web` runs it after building
// Flutter into `server/public/`.
//
// Every file the app is built from is precached when the worker installs, so
// the app opens with no network from the first visit on, and always from one
// consistent build. A deploy reaches a player as a new worker that precaches
// the new build beside the old one and takes over once no tab still runs the
// old build, or at once when the app asks it to because the engine requires the
// update.

// Paths the game Worker answers itself rather than the app shell: its
// `run_worker_first` routes in wrangler.jsonc, less `/join/*` and `/game/*`,
// which render the app. A navigation to any other path opens the app.
const workerRoutes = [/^\/api\//, /^\/avatars\//, /^\/\.well-known\//, /^\/(health|download|terms|privacy|delete-account|robots\.txt|sitemap\.xml|site\.webmanifest)$/];

module.exports = {
  globDirectory: "server/public",
  swDest: "server/public/sw.js",
  globPatterns: ["index.html", "flutter_bootstrap.js", "main.dart.*", "manifest.json", "favicon.png", "icons/**", "assets/**"],
  globIgnores: ["**/*.map", "**/*.symbols"],
  // `main.dart.js` alone is several megabytes, and a game's assets may be too.
  // A file over the limit would be left out with only a warning, and the app
  // would then fail offline, so the limit is set well above anything expected.
  maximumFileSizeToCacheInBytes: 32 * 1024 * 1024,
  navigateFallback: "index.html",
  navigateFallbackDenylist: workerRoutes,
  runtimeCaching: [
    {
      // CanvasKit and the Firebase JS SDK load from Google's CDN at URLs that
      // name their version, so a cached copy is never stale. The page adds what
      // a first visit loaded before this worker controlled it (see
      // web/flutter_bootstrap.js), under the same cache name.
      urlPattern: /^https:\/\/www\.gstatic\.com\/(flutter-canvaskit|firebasejs)\//,
      handler: "CacheFirst",
      options: { cacheName: "eigen-cdn", cacheableResponse: { statuses: [200] } },
    },
  ],
  skipWaiting: false,
  clientsClaim: true,
  cleanupOutdatedCaches: true,
  inlineWorkboxRuntime: true,
  sourcemap: false,
  mode: "production",
};
