/**
 * Default Privacy Policy.
 *
 * A neutral starting template, NOT legal advice. The operator publishing the
 * game is responsible for its accuracy and for having it reviewed. It describes
 * ONLY what the engine itself collects; if you add analytics, advertising,
 * payments, or any other processing, you must say so here. To replace it, pass
 * your own HTML fragment as `site.legal.privacy`.
 *
 * Two entries to check against what you actually ship: the “Diagnostics” bullet
 * assumes crash reporting (remove it if you have none), and “What we do not
 * collect” is deliberately scoped to advertising rather than denying analytics
 * outright, so do not widen it into a claim your app cannot support.
 */

import type { LegalProps } from "./props.js";

export function Privacy({ appName, operator }: LegalProps) {
  const mailto = `mailto:${operator.contactEmail}`;
  return (
    <>
      <h1>Privacy Policy</h1>
      <p class="meta">Effective {operator.effectiveDate}</p>

      <p class="lead">
        This policy explains what {operator.name} collects when you use {appName} (the “Service”), why, and what control you have over it.
      </p>

      <h2>What we collect</h2>
      <ul>
        <li>
          <strong>Account identifier.</strong> A unique id issued when you sign in, provided by our authentication provider. If you sign in with an email address or a third-party account, we receive an identifier associated with it.
        </li>
        <li>
          <strong>Display name.</strong> The name you choose, shown to other players.
        </li>
        <li>
          <strong>Profile image.</strong> Optional. Only stored if you upload one.
        </li>
        <li>
          <strong>Gameplay data.</strong> Games you take part in, the moves made, results, ratings, and timestamps.
        </li>
        <li>
          <strong>Social connections.</strong> Friend requests you send or accept, and players you block.
        </li>
        <li>
          <strong>Device registration.</strong> An identifier for your device's messaging service, so we can send you notifications about your games. Removed when you sign out or disable notifications.
        </li>
        <li>
          <strong>Operational logs.</strong> Standard request logs generated by our hosting provider, used to keep the Service secure and working.
        </li>
        <li>
          <strong>Diagnostics.</strong> Crash reports and basic device information, such as device model and operating-system version, used to find and fix faults.
        </li>
      </ul>

      <h2>What we do not collect</h2>
      <p>We do not collect your contacts or your location. We do not serve advertising in the Service, we do not build advertising profiles, and we do not sell your data.</p>

      <h2>Why we use it</h2>
      <ul>
        <li>To run matches, and to show your name and avatar to the players you are matched with.</li>
        <li>To maintain ratings, rankings, and game history.</li>
        <li>To send notifications about games you are part of.</li>
        <li>To detect and prevent abuse, cheating, and technical faults.</li>
        <li>To meet legal obligations.</li>
      </ul>

      <h2>What other players can see</h2>
      <p>Your display name, profile image, rating, and the games you play with someone are visible to the players involved. Do not use a display name or image you would not want an opponent to see.</p>

      <h2>Sharing</h2>
      <p>
        We do not sell your personal data. We share it only with service providers who operate the Service on our behalf (authentication, hosting and storage, and push-notification delivery) and only as far as needed to provide it. We may also disclose data where legally required, or to protect the rights and safety of
        players and {operator.name}.
      </p>

      <h2>Retention</h2>
      <p>
        We keep your account data for as long as your account exists. Guest accounts that go unused are removed automatically after a period of inactivity. When you delete your account, we remove your profile, avatar, device registrations, and social connections immediately; records of completed games may be retained
        in a form that no longer identifies you, because they also form part of your opponents' history.
      </p>

      <h2>Your choices</h2>
      <ul>
        <li>
          <strong>Access and correction.</strong> You can view and edit your display name and profile image in the app.
        </li>
        <li>
          <strong>Deletion.</strong> You can delete your account from within the app; see <a href="/delete-account">Delete Account</a>.
        </li>
        <li>
          <strong>Notifications.</strong> You can turn notifications off in the app or in your device settings.
        </li>
      </ul>
      <p>Depending on where you live, you may have further rights over your personal data, including the right to object to or restrict processing and to lodge a complaint with a supervisory authority. Contact us to exercise them.</p>

      <h2>Children</h2>
      <p>The Service is not directed at children below the age at which parental consent is required for online services in their country. We do not knowingly collect data from such children. If you believe a child has provided us data, contact us and we will remove it.</p>

      <h2>International transfers</h2>
      <p>The Service runs on distributed infrastructure, so your data may be processed in countries other than your own. Where required, we rely on appropriate safeguards for those transfers.</p>

      <h2>Security</h2>
      <p>We use industry-standard measures to protect your data in transit and at rest. No system is perfectly secure, and we cannot guarantee absolute security.</p>

      <h2>Changes</h2>
      <p>We may update this policy. We will revise the effective date above and communicate material changes through the Service.</p>

      <h2>Contact</h2>
      <p>
        Privacy questions and requests can be sent to <a href={mailto}>{operator.contactEmail}</a>. {operator.name} is the controller responsible for this data, under the laws of {operator.jurisdiction}.
      </p>
    </>
  );
}
