// Regenerates the `.ts` module beside each bundled `.woff2`.
//
// The `.woff2` is the source of truth: it is what a font tool can open, what a
// diff can be reasoned about, and what the docs site serves byte-for-byte. The
// `.ts` exists because `vitest-pool-workers` resolves worker-side modules
// outside vite's plugin graph, so a bundler-loaded binary import is empty under
// test — the font route would answer 500 in the suite while working in
// production. A string literal is the one representation every pipeline agrees
// on. See `src/site/fonts/README.md`.
//
//   node scripts/encode-fonts.mjs           rewrite the modules
//   node scripts/encode-fonts.mjs --check   fail if they are out of date
//
// `--check` runs in CI, for the same reason `eigen-contract --check` does: a
// generated file that nobody verifies is a generated file that silently drifts.

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const FONTS = resolve(dirname(fileURLToPath(import.meta.url)), "../src/site/fonts");
const check = process.argv.includes("--check");

const moduleFor = (base64) => `/**
 * Generated by \`scripts/encode-fonts.mjs\` from the \`.woff2\` beside it. Do not
 * edit; run \`pnpm run fonts\` after replacing the font, and bump \`VERSION\` in
 * \`../fonts.ts\` so returning visitors are not held on the old bytes by the
 * immutable cache header.
 */

export default "${base64}";
`;

let stale = 0;
for (const file of readdirSync(FONTS)
  .filter((f) => f.endsWith(".woff2"))
  .sort()) {
  const target = join(FONTS, `${file.replace(/\.woff2$/, "")}.ts`);
  const expected = moduleFor(readFileSync(join(FONTS, file)).toString("base64"));

  let actual = null;
  try {
    actual = readFileSync(target, "utf8");
  } catch {
    // Missing counts as stale, and as something to write.
  }

  if (actual === expected) continue;
  stale += 1;

  if (check) {
    console.error(`encode-fonts: ${file} does not match its module. Run \`pnpm run fonts\`.`);
    continue;
  }
  writeFileSync(target, expected);
  console.log(`encode-fonts: wrote ${target.slice(FONTS.length + 1)}`);
}

if (check && stale > 0) process.exitCode = 1;
else if (check) console.log("encode-fonts: modules match their fonts");
