/** Shape of the drizzle-kit `durable-sqlite` migrations bundle (generated
 * `migrations.js` — regenerated by `pnpm db:generate:do`, never edited). The
 * `.sql` import inside it is inlined as text by the tsup build. */
declare const migrations: {
  journal: { entries: { idx: number; when: number; tag: string; breakpoints: boolean }[] };
  migrations: Record<string, string>;
};
export default migrations;
