/**
 * `commit()` is the pure, serialized heart of the engine. One state transition
 * in, one {@link CommitPlan}
 * (or {@link Rejected}) out. Zero I/O, zero platform imports, injected clock:
 * the host (a Durable Object) loads the snapshot, calls this, and applies the
 * plan in one storage transaction.
 *
 * The pipeline is: status/pending/deadline guards, bank deduction, timeout
 * abstain-and-zero, then the deadline precedence chain. Two rules are worth
 * knowing before reading further: the grace window is the single
 * {@link DEADLINE_GRACE_MS} constant applied in one place, and a stale
 * `expectedVersion` is arbitrated by the same-view rule rather than flatly
 * rejected. Versions stay strictly serial: the same-view rule governs
 * acceptance only, and every accepted action commits as `state.version + 1`
 * in arrival order.
 */

import { type ActionType, type Envelope, type GameRules, IllegalMoveError, type JsonObject, type LifecycleAction, type OutcomeEntry, type TransitionCause } from "@eigeninteractive/rules";
import { GameBugError, type Rejected, reject } from "./errors.js";
import { assertBudgetPending, assertForfeitPending, assertHookState, assertPendingIdentified, type SeatView, sameView } from "./guards.js";
import { fanOutObservations, type ObservationFrame } from "./observe.js";
import type { RatingDelta } from "./ratings.js";
import { deriveRng } from "./rng.js";
import { parseClientPayload, parseStoredPayload } from "./schema.js";
import { computeNextDeadline, DEADLINE_GRACE_MS, deadlineExpired, deductBank } from "./timing.js";

// ── Snapshot types (what the host loads) ──────────────────────────────────────

export type GameStatus = "waiting" | "ready" | "active" | "finished" | "aborted";

/** The game's standing configuration: the DO `meta` snapshot. */
export interface GameRow {
  status: GameStatus;
  schemaVersion: number;
  /** Stored creation config; parsed against the version unit's config schema
   * before any hook sees it. */
  config: JsonObject;
  turnSeconds: number | null;
  budgetSeconds: number | null;
  incrementSeconds: number | null;
  rated: boolean;
  ratingPool: string | null;
}

/** One seat of the roster. Both ids null ⇒ the account was purged mid-game
 * (the seat plays on as "Deleted User" for display, but can never act). */
export interface Seat {
  playerIndex: number;
  userId: string | null;
  botId: string | null;
  type: "human" | "bot";
}

/** The latest committed transition: state plus the engine-owned clocks. All
 * instants are epoch milliseconds. */
export interface StateRow {
  version: number;
  state: JsonObject;
  pending: number[];
  rngSeed: string;
  /** The true turn deadline shown to clients; the alarm arms at
   * `deadline + grace`. */
  deadline: number | null;
  /** Per-seat budget banks (ms), budget mode only. */
  playerTimes: number[] | null;
  turnStartedAt: number | null;
}

// ── Intents ───────────────────────────────────────────────────────────────────

/** What the host asks the kernel to do: the kernel-facing half of a
 * `Command` (authorization already happened at the edge; dedupe at the DO). */
export type Intent =
  | {
      kind: "start";
      /** The game's base RNG seed, freshly generated by the host
       * (`randomSeed()`); stored on v0 and copied to every later row. */
      seed: string;
    }
  | {
      kind: "action";
      seat: number;
      /** The version the client computed the move against. Equal to the
       * current version in the common case; a *lower* value is arbitrated by
       * the same-view rule. */
      expectedVersion: number;
      /** The raw move payload, parsed against the unit's action schema. */
      data: unknown;
      actor: "user" | "bot";
    }
  | { kind: "lifecycle"; type: "timeout" }
  /** `forfeit` = a voluntary resign (a user action); `autoForfeit` = the
   * engine-driven variant (account purge; identity-less system action). */
  | { kind: "lifecycle"; type: "forfeit" | "autoForfeit"; seat: number };

export interface CommitInput {
  game: GameRow;
  /** The latest transition, or null before v0 (only a `start` intent is
   * meaningful then). */
  state: StateRow | null;
  roster: Seat[];
  intent: Intent;
  /** The commit instant (epoch ms), sampled once by the host and never read
   * here. */
  now: number;
  /** The version unit for the game's `schemaVersion`, already resolved by
   * the host from the `GameModule.versions` map. */
  rules: GameRules;
  /**
   * Same-view material for a stale game action: the acting seat's stored
   * frames at `expectedVersion` and at the current version. Only consulted
   * when `intent.expectedVersion < state.version`; if absent (or either
   * frame is missing, e.g. compacted away), the stale action is rejected
   * conservatively.
   */
  staleViews?: {
    expected: SeatView | null;
    current: SeatView | null;
  };
}

// ── Plan (what the host applies) ──────────────────────────────────────────────

/** The action-log entry for a transition. Null only for the start transition
 * (v0), which no action produced. `playerIndex` is the performer's seat, and
 * null for identity-less system actions (timeout, auto-forfeit).
 *
 * The `ratings` variant is engine-owned, never produced by `commit()`: the
 * host appends it as the post-finish ratings transition (step 3) once
 * the D1 apply returns the deltas. Game hooks never see it; its data is the
 * engine's, not the game's opaque payload. */
export type TransitionAction = { type: "user" | "bot"; kind: "game"; data: JsonObject; playerIndex: number } | { type: ActionType; kind: "lifecycle"; data: LifecycleAction; playerIndex: number | null } | { type: "system"; kind: "ratings"; data: { deltas: RatingDelta[] }; playerIndex: null };

/** A push/wake the host should attempt post-commit (single attempt + error
 * log, with no retry machinery in v1). The kernel names seats; the host resolves
 * delivery (FCM targets, bot webhook vs local bot). */
export type Effect = { kind: "wakeBot"; seat: number; botId: string } | { kind: "notifyTurn"; seat: number; userId: string } | { kind: "notifyFinished"; userIds: string[] };

export interface CommitPlan {
  /** The next transition row, already versioned (`v+1`, or 0 for start). */
  nextState: StateRow;
  action: TransitionAction | null;
  /** Per-seat projected frames (identified seats only), persisted with the
   * transition, fanned out over sockets. No raw state escapes the kernel. */
  frames: ObservationFrame[];
  /** Per-seat results when this transition ends the game, else null.
   *
   * Rating deltas are deliberately NOT here: they depend on global cross-game
   * priors (D1-domain data the kernel must never need). The D1 applier
   * computes them inside the rating CAS via `computeRatings` (ratings.ts) and
   * the host delivers them as a follow-up versioned ratings transition. */
  outcomes: OutcomeEntry[] | null;
  /** The instant the DO must arm its alarm at, the true deadline plus the
   * grace window, or null to clear it. */
  alarm: number | null;
  effects: Effect[];
}

/** Type guard: did `commit()` refuse the intent? */
export function isRejected(result: CommitPlan | Rejected): result is Rejected {
  return "rejected" in result;
}

// ── commit() ──────────────────────────────────────────────────────────────────

export function commit(input: CommitInput): CommitPlan | Rejected {
  switch (input.intent.kind) {
    case "start":
      return commitStart(input, input.intent);
    case "action":
      return commitAction(input, input.intent);
    case "lifecycle":
      return input.intent.type === "timeout" ? commitTimeout(input, input.intent) : commitForfeit(input, input.intent);
  }
}

function commitStart(input: CommitInput, intent: Extract<Intent, { kind: "start" }>): CommitPlan | Rejected {
  const { game, roster, rules } = input;
  // Idempotent like the old engine_commit_start: a duplicate start (fresh
  // commandId, game already running) is a clean no-op, not an error.
  if (game.status === "active") {
    return reject("abstain", "Game is already active");
  }
  if (game.status !== "ready") {
    return reject("notReady", "Game is not ready to start");
  }
  if (!intent.seed) {
    throw new GameBugError("start intent carries an empty rng seed");
  }

  const config = parseStoredPayload(rules.schemas.config, game.config, "config", game.schemaVersion);
  const envelope = rules.initialState({
    config,
    rng: deriveRng(intent.seed, 0),
    playerCount: roster.length,
  });

  const playerTimes = game.budgetSeconds !== null ? roster.map(() => (game.budgetSeconds as number) * 1000) : null;

  return buildPlan(input, {
    version: 0,
    seed: intent.seed,
    envelope,
    config,
    action: null,
    cause: null,
    playerTimes,
  });
}

function commitAction(input: CommitInput, intent: Extract<Intent, { kind: "action" }>): CommitPlan | Rejected {
  const { game, state, rules, now } = input;
  if (state === null) {
    throw new GameBugError("action intent reached commit() before v0");
  }
  if (game.status !== "active") {
    return reject("notActive", "Game is not active");
  }

  if (intent.expectedVersion > state.version) {
    // The client claims a version the game hasn't reached, which is a protocol bug,
    // but the client-facing remedy is the same resync as any version miss.
    return reject("stateUpdated", `Expected version ${intent.expectedVersion} is ahead of the game ` + `(current ${state.version})`);
  }
  if (intent.expectedVersion < state.version) {
    // The same-view rule: the stale intent transfers iff this seat's
    // own projected view is unchanged between the two versions. Missing
    // frames (never stored, or already compacted) reject conservatively.
    const views = input.staleViews;
    if (!views?.expected || !views.current || !sameView(views.expected, views.current)) {
      return reject("stateUpdated", "State updated, try again");
    }
  }

  if (deadlineExpired(state.deadline, now)) {
    return reject("expired", "Turn has expired");
  }
  if (!state.pending.includes(intent.seat)) {
    return reject("notPending", "Not your turn");
  }

  const config = parseStoredPayload(rules.schemas.config, game.config, "config", game.schemaVersion);
  const priorState = parseStoredPayload(rules.schemas.state, state.state, "state", game.schemaVersion);
  const parsed = parseClientPayload(rules.schemas.action, intent.data, "action");
  if (!parsed.ok) {
    return reject("invalidPayload", parsed.message);
  }

  let envelope: Envelope;
  try {
    envelope = rules.applyAction({
      state: priorState,
      pending: state.pending,
      data: parsed.value,
      playerIndex: intent.seat,
      rng: deriveRng(state.rngSeed, state.version + 1),
      config,
    });
  } catch (error) {
    if (error instanceof IllegalMoveError) {
      return reject("illegalMove", error.message || "Illegal move");
    }
    throw error;
  }

  // Bank deduction: budget mode, no per-action override, game not ending.
  // The grace forgives acceptance, never time charged.
  let playerTimes = state.playerTimes;
  if (game.budgetSeconds !== null && envelope.turnSeconds === undefined && envelope.outcome === undefined) {
    if (playerTimes === null) {
      throw new GameBugError("budget-timed game has no playerTimes banks");
    }
    playerTimes = deductBank(playerTimes, intent.seat, now, state.turnStartedAt, game.incrementSeconds);
  }

  const data = parsed.value;
  return buildPlan(input, {
    version: state.version + 1,
    seed: state.rngSeed,
    envelope,
    config,
    action: {
      type: intent.actor,
      kind: "game",
      data,
      playerIndex: intent.seat,
    },
    cause: { kind: "game", data, playerIndex: intent.seat },
    playerTimes,
    actingSeat: intent.seat,
  });
}

function commitTimeout(input: CommitInput, _intent: Extract<Intent, { kind: "lifecycle"; type: "timeout" }>): CommitPlan | Rejected {
  const { game, state, rules, now } = input;
  if (state === null) {
    throw new GameBugError("timeout intent reached commit() before v0");
  }
  // A timeout that lost its race abstains: the alarm and a latent on-time
  // action both fire; whichever commits first wins and the loser no-ops.
  if (game.status !== "active") {
    return reject("abstain", "Game is no longer active");
  }
  if (!deadlineExpired(state.deadline, now)) {
    return reject("abstain", "Deadline has not genuinely expired");
  }

  const config = parseStoredPayload(rules.schemas.config, game.config, "config", game.schemaVersion);
  const priorState = parseStoredPayload(rules.schemas.state, state.state, "state", game.schemaVersion);

  // Every pending seat shared the single expired deadline: all of them timed
  // out. One identity-less system transition resolves the whole set, and the
  // hook decides holistically (eliminate, skip, even a draw).
  const data: LifecycleAction = { type: "timeout" };
  const envelope = rules.applyLifecycle({
    state: priorState,
    pending: state.pending,
    type: "timeout",
    data,
    rng: deriveRng(state.rngSeed, state.version + 1),
    config,
  });

  let playerTimes = state.playerTimes;
  if (game.budgetSeconds !== null && playerTimes !== null) {
    playerTimes = [...playerTimes];
    for (const seat of state.pending) playerTimes[seat] = 0;
  }

  return buildPlan(input, {
    version: state.version + 1,
    seed: state.rngSeed,
    envelope,
    config,
    action: {
      type: "system",
      kind: "lifecycle",
      data,
      playerIndex: null,
    },
    cause: { kind: "lifecycle", data },
    playerTimes,
  });
}

function commitForfeit(input: CommitInput, intent: Extract<Intent, { kind: "lifecycle"; type: "forfeit" | "autoForfeit" }>): CommitPlan | Rejected {
  const { game, state, rules } = input;
  if (state === null) {
    throw new GameBugError("forfeit intent reached commit() before v0");
  }
  if (game.status !== "active") {
    return reject("notActive", "Game is not active");
  }

  const config = parseStoredPayload(rules.schemas.config, game.config, "config", game.schemaVersion);
  const priorState = parseStoredPayload(rules.schemas.state, state.state, "state", game.schemaVersion);

  // Unconditional intent: no deadline/pending/version guard, banks untouched.
  const data: LifecycleAction = {
    type: intent.type,
    playerIndex: intent.seat,
  };
  const envelope = rules.applyLifecycle({
    state: priorState,
    pending: state.pending,
    type: intent.type,
    data,
    rng: deriveRng(state.rngSeed, state.version + 1),
    config,
  });
  assertForfeitPending(intent.seat, envelope, game.schemaVersion);

  return buildPlan(input, {
    version: state.version + 1,
    seed: state.rngSeed,
    envelope,
    config,
    action: {
      // A resign is the user's own action; the engine-driven variant is
      // identity-less system, exactly like the old commit modes.
      type: intent.type === "forfeit" ? "user" : "system",
      kind: "lifecycle",
      data,
      playerIndex: intent.type === "forfeit" ? intent.seat : null,
    },
    cause: { kind: "lifecycle", data },
    playerTimes: state.playerTimes,
    actingSeat: intent.type === "forfeit" ? intent.seat : undefined,
  });
}

// ── Shared transition builder ─────────────────────────────────────────────────

function buildPlan(
  input: CommitInput,
  t: {
    version: number;
    seed: string;
    envelope: Envelope;
    config: JsonObject;
    action: TransitionAction | null;
    cause: TransitionCause;
    playerTimes: number[] | null;
    actingSeat?: number;
  },
): CommitPlan {
  const { game, roster, rules, now } = input;
  const { envelope } = t;

  assertHookState(rules.schemas, envelope, game.schemaVersion);
  assertBudgetPending(game.budgetSeconds, envelope, game.schemaVersion);
  assertPendingIdentified(roster, envelope, game.schemaVersion);

  const outcomes = validateOutcomes(envelope, roster, game.schemaVersion);

  const next = computeNextDeadline({
    now,
    gameOver: outcomes !== null,
    actionSeconds: envelope.turnSeconds ?? null,
    budgetSeconds: game.budgetSeconds,
    turnSeconds: game.turnSeconds,
    newPending: envelope.pendingPlayers,
    newPlayerTimes: t.playerTimes,
  });

  // No viewer, no frame: a seat purged mid-game has neither identity, so its
  // projection would be unreadable forever (mirrors the old slice filter).
  const identified = new Set(roster.filter((s) => s.userId !== null || s.botId !== null).map((s) => s.playerIndex));
  const frames = fanOutObservations(rules, {
    state: envelope.state,
    pending: envelope.pendingPlayers,
    participantCount: roster.length,
    config: t.config,
    cause: t.cause,
    isReplay: false,
  }).filter((frame) => identified.has(frame.playerIndex));

  return {
    nextState: {
      version: t.version,
      state: envelope.state,
      pending: envelope.pendingPlayers,
      rngSeed: t.seed,
      deadline: next.deadline,
      playerTimes: t.playerTimes,
      turnStartedAt: next.turnStartedAt,
    },
    action: t.action,
    frames,
    outcomes,
    alarm: next.deadline === null ? null : next.deadline + DEADLINE_GRACE_MS,
    effects: computeEffects(roster, envelope, outcomes, t.actingSeat),
  };
}

/** Runtime shape check over the game-supplied outcome. Hooks are typed, but
 * an outcome drives ratings and permanent records, so a malformed entry is
 * caught at the source like every other hook bug. */
function validateOutcomes(envelope: Envelope, roster: readonly Seat[], schemaVersion: number): OutcomeEntry[] | null {
  const outcome = envelope.outcome;
  if (outcome === undefined) return null;
  if (!Array.isArray(outcome) || outcome.length === 0) {
    throw new GameBugError(`Hook returned a non-array or empty outcome (schemaVersion ${schemaVersion})`);
  }
  for (const entry of outcome) {
    if (!roster.some((s) => s.playerIndex === entry.playerIndex)) {
      throw new GameBugError(`Outcome references unknown playerIndex ${entry.playerIndex}`);
    }
    if (typeof entry.placement !== "number") {
      throw new GameBugError(`Outcome for playerIndex ${entry.playerIndex} missing required placement`);
    }
    if (typeof entry.teamIndex !== "number") {
      throw new GameBugError(`Outcome for playerIndex ${entry.playerIndex} missing required teamIndex`);
    }
  }
  return outcome;
}

/** Post-commit deliveries: turn notifications / bot wakes for every newly
 * waiting seat except the actor, and a finish notification to every human.
 * The kernel names seats; the host owns delivery and filtering (FCM prefs,
 * local vs server bots). */
function computeEffects(roster: readonly Seat[], envelope: Envelope, outcomes: OutcomeEntry[] | null, actingSeat: number | undefined): Effect[] {
  const bySeat = new Map(roster.map((s) => [s.playerIndex, s]));
  if (outcomes !== null) {
    const userIds = roster.filter((s) => s.userId !== null).map((s) => s.userId as string);
    return userIds.length ? [{ kind: "notifyFinished", userIds: userIds }] : [];
  }
  const effects: Effect[] = [];
  for (const seat of envelope.pendingPlayers) {
    const member = bySeat.get(seat);
    if (!member) continue;
    if (member.botId !== null) {
      // A bot always needs its wake, even the acting seat re-entering pending
      // (an extra turn): a bot has no live client to act on its own, so its
      // only signal to move again is a fresh wake. A duplicate is harmless
      // (the in-DO self-apply dedupes on commandId; an external wake carries
      // the same version and loses the version check at commit).
      effects.push({ kind: "wakeBot", seat, botId: member.botId });
    } else if (seat !== actingSeat && member.userId !== null) {
      // A human actor is live in-app and needs no push; only newly-waiting
      // humans are notified.
      effects.push({ kind: "notifyTurn", seat, userId: member.userId });
    }
  }
  return effects;
}
