/**
 * The D1 schema, the global store: identity, social,
 * bots, ratings, and game summary rows. A read-model + registry, never an
 * arbiter: live game truth is each game's DO; D1 is what lists, lobbies,
 * leaderboards, and profiles read. Never wake a DO to serve a read.
 *
 * Kept deliberately narrow: one `users` row per identity, outcomes folded into
 * the games row as JSON, and no identity denormalized onto games (the batch
 * `players?ids=` endpoint plus the client's persisted cache covers that, so
 * a display-name change never has to be rewritten across history).
 *
 * Firebase uids are TEXT keys; engine-generated ids are UUID strings; instants
 * are epoch milliseconds.
 *
 * Migrations are generated by drizzle-kit and applied with
 * `wrangler d1 migrations apply`, never at runtime.
 */

import type { GameStatus, Seat } from "@eigeninteractive/kernel";
import type { GameAccess, JsonObject, OutcomeEntry } from "@eigeninteractive/rules";
import { sql } from "drizzle-orm";
import { check, index, integer, real, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";
import type { GameOrigin } from "../protocol.js";

/** One row per identity, public and private fields together; authorization is
 * enforced in the routes, not by table separation. Provisioned on first sight
 * of a verified Firebase token; `avatar_url` defaults to the provider photo
 * (null ⇒ client renders initials). */
export const users = sqliteTable(
  "users",
  {
    /** The Firebase uid, stable across guest → permanent upgrades. */
    id: text().primaryKey(),
    username: text().notNull().unique(),
    /** Null for guests until they convert; UNIQUE tolerates multiple NULLs. */
    email: text().unique(),
    displayName: text().notNull(),
    avatarUrl: text(),
    isAnonymous: integer({ mode: "boolean" }).notNull(),
    createdAt: integer().notNull(),
    updatedAt: integer().notNull(),
  },
  (t) => [index("idx_users_username").on(t.username)],
);

/** The game summary/read-model row (created worker-direct, before the
 * DO exists;: updated post-commit from DO effects, accepted staleness).
 *
 * Every write after the create carries the Durable Object's `seq` for the
 * commit it mirrors and applies only when that is not older than the row's.
 * The mirror is dispatched without being awaited and retried, so two writes for
 * one game can land in either order; ordering them by the object's own counter
 * is what keeps a late, older write from regressing the row. */
export const games = sqliteTable(
  "games",
  {
    id: text().primaryKey(),
    createdBy: text(),
    status: text().$type<GameStatus>().notNull(),
    access: text().$type<GameAccess>().notNull(),
    /** Where the game is played (see `GameOrigin`). Immutable, and defaulted so
     * that the online create — every create but one — never mentions it.
     * CHECKed unlike `status`/`access` because this column decides whether a
     * request may act on a bot's seat: a row that drifted to a value nothing
     * recognizes must fail the insert, not open a trust rule. */
    origin: text().$type<GameOrigin>().notNull().default("online"),
    schemaVersion: integer().notNull(),
    config: text({ mode: "json" }).$type<JsonObject>().notNull(),
    /** Exactly one timing mode: turn XOR budget XOR untimed (worker policy
     * validates; no CHECK, since D1 is display and the DO is integrity). */
    turnSeconds: integer(),
    budgetSeconds: integer(),
    incrementSeconds: integer(),
    rated: integer({ mode: "boolean" }).notNull(),
    ratingPool: text(),
    minPlayers: integer().notNull(),
    maxPlayers: integer().notNull(),
    shortCode: text().notNull().unique(),
    /** Dashboard hints ("your turn", countdowns); display-only staleness OK. */
    pendingPlayers: text({ mode: "json" }).$type<number[] | null>(),
    turnDeadline: integer(),
    /** Folded former game_outcomes table, written once by the finish apply. */
    outcomes: text({ mode: "json" }).$type<OutcomeEntry[] | null>(),
    /** The game's revision: the Durable Object's `meta.seq` as of the commit
     * this row mirrors. 0 at create, when no object exists yet. */
    seq: integer().notNull().default(0),
    /** The D1 apply's idempotency key; set when the apply lands. */
    finishId: text(),
    /** Stamped by the finish apply; history lists sort by it. An aborted game
     * keeps no roster, so it is in no account's history and never gets one. */
    finishedAt: integer(),
    /** Where this game sits in the order finishes COMMITTED, assigned once by
     * the finish apply as one more than the largest so far. The history sync
     * cursor. Not `finishedAt`: that instant is chosen before the write commits,
     * and finishes commit out of order (the rating compare-and-swap retries and
     * a crashed apply is re-poked), so a device that had synced past a later
     * timestamp would never see an earlier-stamped game that committed after. */
    finishSeq: integer(),
    /** Cold-tier seam: NULL = history lives in the game's DO. V1 never writes
     * or reads it; the future cold-tier sweep starts stamping it. */
    archivedAt: integer(),
    createdAt: integer().notNull(),
    updatedAt: integer().notNull(),
  },
  (t) => [
    index("idx_games_status_access").on(t.status, t.access),
    index("idx_games_created_by").on(t.createdBy),
    // The lobby page: public joinable games, newest first (ported partial index).
    index("idx_games_lobby").on(t.createdAt).where(sql`access = 'public' AND status IN ('waiting', 'ready')`),
    // Serves both the next number's MAX() and the history sync's range read.
    uniqueIndex("idx_games_finish_seq").on(t.finishSeq).where(sql`finish_seq IS NOT NULL`),
    check("games_origin_valid", sql`${t.origin} IN ('online', 'local')`),
  ],
);

/** The roster join table: one row per seat, and the indexed access path for
 * "games of user X". Written at create/join/leave alongside the games row; the
 * DO's own roster remains the integrity copy. The game-scoped unique indexes
 * are what actually guard the join race. */
export const participants = sqliteTable(
  "participants",
  {
    id: text().primaryKey(),
    gameId: text().notNull(),
    /** Exactly one of user_id/bot_id for a live identity; both may be NULL
     * after an account purge (worker-enforced, since D1 carries no CHECKs). */
    userId: text(),
    botId: text(),
    playerIndex: integer().notNull(),
    type: text().$type<Seat["type"]>().notNull(),
    createdAt: integer().notNull(),
  },
  (t) => [uniqueIndex("idx_participants_unique").on(t.gameId, t.userId).where(sql`user_id IS NOT NULL`), uniqueIndex("idx_participants_player_index").on(t.gameId, t.playerIndex), index("idx_participants_user_id").on(t.userId), index("idx_participants_game_id").on(t.gameId)],
);

/** Friends and blocks: one row per pair, in canonical order
 * (`user_id_1 < user_id_2`, worker-enforced) + UNIQUE, so a relationship can
 * never exist twice in opposite orientations. */
export const relationships = sqliteTable(
  "relationships",
  {
    id: text().primaryKey(),
    userId1: text().notNull(),
    userId2: text().notNull(),
    initiatedBy: text().notNull(),
    /** `blocked` rows are load-bearing: `d1/blocks.ts` reads them to hide
     * games and refuse seats in both directions. `initiated_by` names the
     * blocker, so only they can unblock. */
    status: text().$type<"pending" | "accepted" | "blocked">().notNull(),
    createdAt: integer().notNull(),
    updatedAt: integer().notNull(),
  },
  (t) => [uniqueIndex("idx_relationships_pair").on(t.userId1, t.userId2), index("idx_relationships_user2").on(t.userId2)],
);

/** How a bot's moves are produced, the dispatch discriminator:
 * - `engine`: the brain ships in the game's `GameModule` as
 *   `GameRules.botActions[username]`, run in-process by the DO;
 * - `external`: the bot is hosted elsewhere and woken over HMAC (`webhook_url`
 *   is then required);
 * - `local`: client-driven (future offline-solo transcript import), a
 *   registry row for identity only, never dispatched server-side. */
export type BotType = "engine" | "external" | "local";

/** Bot registry. `type` selects the dispatch path; `webhook_url` is
 * required for (and only for) `external`. `username` is the stable,
 * human-readable key the game's `botActions` map is keyed by for `engine`
 * bots. */
export const bots = sqliteTable(
  "bots",
  {
    id: text().primaryKey(),
    username: text().notNull().unique(),
    displayName: text().notNull(),
    avatarUrl: text(),
    /** Highest game schema this bot supports: the seating gate. */
    schemaVersion: integer().notNull(),
    type: text().$type<BotType>().notNull(),
    webhookUrl: text(),
    ratedEligible: integer({ mode: "boolean" }).notNull(),
    config: text({ mode: "json" }).$type<JsonObject>().notNull(),
    createdAt: integer().notNull(),
  },
  (t) => [
    // A webhook is present iff the bot is external, so the type/columns stay a
    // valid discriminated union at the storage layer, not just in TS.
    check("bots_webhook_matches_type", sql`(${t.type} = 'external') = (${t.webhookUrl} IS NOT NULL)`),
    check("bots_type_valid", sql`${t.type} IN ('engine', 'external', 'local')`),
  ],
);

/** Per-identity per-pool OpenSkill rating. Exactly one of user_id/bot_id is
 * set. `revision` is the CAS counter: the finish apply reads
 * (mu, sigma, revision), computes in TS, and writes a `rating_history` row
 * stamped with the revision it read, whose UNIQUE index is what rejects a
 * concurrent finish (see `rating_history.revision_before`). The fix for the
 * legacy concurrent-finish lost-update bug. */
export const playerRatings = sqliteTable(
  "player_ratings",
  {
    id: text().primaryKey(),
    userId: text(),
    botId: text(),
    pool: text().notNull(),
    mu: real().notNull(),
    sigma: real().notNull(),
    /** max(0, round((mu − 3σ) · 40)), denormalized for leaderboards. */
    displayRating: integer().notNull(),
    revision: integer().notNull(),
    createdAt: integer().notNull(),
    updatedAt: integer().notNull(),
  },
  (t) => [uniqueIndex("idx_player_ratings_user_pool").on(t.userId, t.pool).where(sql`user_id IS NOT NULL`), uniqueIndex("idx_player_ratings_bot_pool").on(t.botId, t.pool).where(sql`bot_id IS NOT NULL`)],
);

/** Immutable per-game rating log, and the concurrency control for rating
 * writes. A client learns its own changes from the finished games it syncs,
 * which carry every identity's delta, so nothing lists this table per user.
 *
 * Two unique indexes, guarding two different races:
 *
 * - `(game_id, identity)`: idempotence. A re-poked apply for the SAME game
 *   cannot double-write. Paired with `finish_id`.
 * - `(identity, pool, revision_before)`: the CAS. Two finishes of DIFFERENT
 *   games sharing a player both read revision 7 and both try to log
 *   `revision_before = 7`; the second violates this index, its batch rolls
 *   back, and the apply recomputes against fresh priors. This is what makes
 *   the lost update impossible.
 *
 * The CAS lives here rather than on the `player_ratings` UPDATE because
 * SQLite has no in-transaction abort primitive to reach for: an
 * `UPDATE ... WHERE revision = ?` that matches nothing silently succeeds,
 * so a guard there would let the other statements in the batch commit
 * against stale priors. A unique-index violation is an error, and an error
 * is what rolls a `batch()` back. */
export const ratingHistory = sqliteTable(
  "rating_history",
  {
    id: text().primaryKey(),
    userId: text(),
    botId: text(),
    gameId: text().notNull(),
    pool: text().notNull(),
    finishId: text().notNull(),
    /** The `player_ratings.revision` this delta was computed against, 0 for
     * an identity that had no rating row yet. The post-write revision is
     * always this + 1, so the column doubles as the per-identity ordering of
     * the log. */
    revisionBefore: integer().notNull(),
    muBefore: real().notNull(),
    sigmaBefore: real().notNull(),
    displayBefore: integer().notNull(),
    muAfter: real().notNull(),
    sigmaAfter: real().notNull(),
    displayAfter: integer().notNull(),
    displayChange: integer().notNull(),
    createdAt: integer().notNull(),
  },
  (t) => [
    uniqueIndex("idx_rating_history_game_user").on(t.gameId, t.userId).where(sql`user_id IS NOT NULL`),
    uniqueIndex("idx_rating_history_game_bot").on(t.gameId, t.botId).where(sql`bot_id IS NOT NULL`),
    // The CAS (see the table docstring). Partial, because exactly one
    // identity column is set per row.
    uniqueIndex("idx_rating_history_user_cas").on(t.userId, t.pool, t.revisionBefore).where(sql`user_id IS NOT NULL`),
    uniqueIndex("idx_rating_history_bot_cas").on(t.botId, t.pool, t.revisionBefore).where(sql`bot_id IS NOT NULL`),
  ],
);

/** FCM push targets, keyed by Firebase Installation ID. */
export const deviceInstallations = sqliteTable(
  "device_installations",
  {
    fid: text().primaryKey(),
    userId: text().notNull(),
    platform: text().$type<"ios" | "android" | "web">().notNull(),
    updatedAt: integer().notNull(),
  },
  (t) => [index("idx_device_installations_user").on(t.userId)],
);

/** Stable identity for the two game-creation routes. The game row, roster,
 * usage, and this receipt are inserted in one D1 batch. */
export const creationOperations = sqliteTable(
  "creation_operations",
  {
    id: text().primaryKey(),
    creatorId: text().notNull(),
    creationId: text().notNull(),
    fingerprint: text().notNull(),
    gameId: text().notNull(),
    shortCode: text().notNull(),
    createdAt: integer().notNull(),
  },
  (t) => [uniqueIndex("idx_creation_operations_creator_id").on(t.creatorId, t.creationId), uniqueIndex("idx_creation_operations_game").on(t.gameId)],
);

/** Immutable commercial content selected when a game is created. */
export const gameContent = sqliteTable(
  "game_content",
  {
    id: text().primaryKey(),
    gameId: text().notNull(),
    collection: text().notNull(),
    itemId: text().notNull(),
    classification: text().$type<"sharedRuleset" | "cosmetic">().notNull(),
    ownership: text().$type<"creator" | "eachParticipant" | "viewer">().notNull(),
  },
  (t) => [uniqueIndex("idx_game_content_item").on(t.gameId, t.collection, t.itemId, t.ownership), index("idx_game_content_game").on(t.gameId)],
);

/** Minimal normalized provider transaction state. The provider token or raw
 * receipt is never stored here. `user_id` is nulled on account deletion while
 * the financial fact remains available for refunds and fraud review. */
export const commerceTransactions = sqliteTable(
  "commerce_transactions",
  {
    id: text().primaryKey(),
    provider: text().notNull(),
    providerTransactionId: text().notNull(),
    userId: text(),
    providerReference: text().notNull(),
    offerKey: text().notNull(),
    kind: text().$type<"oneTime" | "subscription">().notNull(),
    state: text().$type<"pending" | "active" | "grace" | "expired" | "revoked">().notNull(),
    purchasedAt: integer().notNull(),
    validFrom: integer().notNull(),
    validUntil: integer(),
    sealedProviderState: text(),
    acknowledgementState: text().$type<"notRequired" | "pending" | "acknowledged">().notNull(),
    /** When the provider last ANSWERED for this transaction. Staleness. */
    lastReconciledAt: integer(),
    /** When reconciliation last LOOKED at it, answered or not. This is what
     * orders the sweep, so a transaction the provider will not answer for
     * rotates to the back of the queue instead of holding the front of it. */
    reconcileAttemptedAt: integer(),
    /** Consecutive failed attempts. Reset by any successful record, from a
     * sweep, a webhook or a claim. At the configured ceiling the row stops
     * being swept and becomes an operator problem rather than a hot loop. */
    reconcileFailures: integer().notNull().default(0),
    /** Why the last attempt failed, truncated, for the operator surface.
     * Adapters must keep provider tokens out of their error messages. */
    reconcileError: text(),
    createdAt: integer().notNull(),
    updatedAt: integer().notNull(),
  },
  (t) => [uniqueIndex("idx_commerce_transactions_provider_id").on(t.provider, t.providerTransactionId), index("idx_commerce_transactions_user").on(t.userId), index("idx_commerce_transactions_sweep").on(t.provider, t.reconcileFailures, t.reconcileAttemptedAt)],
);

/** Stable account binding used by hosted checkout, customer portals, and
 * provider notifications that identify the provider customer rather than the
 * Eigen account. */
export const commerceProviderAccounts = sqliteTable(
  "commerce_provider_accounts",
  {
    id: text().primaryKey(),
    provider: text().notNull(),
    userId: text().notNull(),
    providerAccountId: text().notNull(),
    createdAt: integer().notNull(),
    updatedAt: integer().notNull(),
  },
  (t) => [uniqueIndex("idx_commerce_provider_accounts_user").on(t.provider, t.userId), uniqueIndex("idx_commerce_provider_accounts_provider_id").on(t.provider, t.providerAccountId)],
);

/** Recoverable hosted-checkout result keyed by a client operation identity.
 * The provider receives the same identity as its idempotency key. */
export const commerceCheckoutOperations = sqliteTable(
  "commerce_checkout_operations",
  {
    id: text().primaryKey(),
    provider: text().notNull(),
    userId: text().notNull(),
    operationId: text().notNull(),
    offerKey: text().notNull(),
    fingerprint: text().notNull(),
    checkoutUrl: text().notNull(),
    expiresAt: integer().notNull(),
    createdAt: integer().notNull(),
  },
  (t) => [uniqueIndex("idx_commerce_checkout_operations_identity").on(t.provider, t.userId, t.operationId)],
);

/** One entitlement granted by one verified transaction. Multiple rows may
 * sustain the same effective entitlement. */
export const entitlementGrants = sqliteTable(
  "entitlement_grants",
  {
    id: text().primaryKey(),
    /** Never null, unlike the transaction that sourced it. An erasure deletes
     * these rows rather than anonymising them: a grant is only ever about a
     * person, where a transaction is also a record of money. */
    userId: text().notNull(),
    entitlementKey: text().notNull(),
    sourceTransactionId: text().notNull(),
    validFrom: integer().notNull(),
    validUntil: integer(),
    revokedAt: integer(),
    createdAt: integer().notNull(),
    updatedAt: integer().notNull(),
  },
  (t) => [uniqueIndex("idx_entitlement_grants_source_key").on(t.sourceTransactionId, t.entitlementKey), index("idx_entitlement_grants_user").on(t.userId, t.entitlementKey)],
);

/** Accepted provider notification identities. Payloads and purchase evidence
 * are deliberately absent; adapters re-fetch current provider state. */
export const commerceEvents = sqliteTable(
  "commerce_events",
  {
    id: text().primaryKey(),
    provider: text().notNull(),
    providerEventId: text().notNull(),
    providerTransactionId: text(),
    receivedAt: integer().notNull(),
    processedAt: integer(),
  },
  (t) => [uniqueIndex("idx_commerce_events_provider_id").on(t.provider, t.providerEventId)],
);

/** Successful commercial metric uses. `slot` is unique within a policy
 * window, enabling an atomic guarded insert instead of a read-then-write cap. */
export const commerceUsage = sqliteTable(
  "commerce_usage",
  {
    id: text().primaryKey(),
    userId: text().notNull(),
    metric: text().$type<"game.create.success" | "games.openCreated" | "bot.game.success" | "analysis.run.success">().notNull(),
    periodKey: text().notNull(),
    slot: integer().notNull(),
    operationId: text().notNull(),
    createdAt: integer().notNull(),
  },
  (t) => [uniqueIndex("idx_commerce_usage_operation").on(t.userId, t.metric, t.operationId), uniqueIndex("idx_commerce_usage_slot").on(t.userId, t.metric, t.periodKey, t.slot), index("idx_commerce_usage_window").on(t.userId, t.metric, t.periodKey)],
);

/** Slots held by live games for the `games.openCreated` limit. Terminal games
 * release their row from the same D1 apply that changes the game status. */
export const commerceCapacity = sqliteTable(
  "commerce_capacity",
  {
    id: text().primaryKey(),
    userId: text().notNull(),
    metric: text().$type<"games.openCreated">().notNull(),
    slot: integer().notNull(),
    gameId: text().notNull(),
    createdAt: integer().notNull(),
  },
  (t) => [uniqueIndex("idx_commerce_capacity_slot").on(t.userId, t.metric, t.slot), uniqueIndex("idx_commerce_capacity_game").on(t.gameId), index("idx_commerce_capacity_user").on(t.userId, t.metric)],
);
