/**
 * The game DO's SQLite schema — one database per game,
 * live *and* finished: after the finish compaction this IS the game's
 * permanent history, field-for-field the future cold-tier blob.
 *
 * Applied by the drizzle `durable-sqlite` migrator inside the DO's
 * `blockConcurrencyWhile` lazy init; the generated `migrations.js` bundle
 * compiles into the worker, so every DO (including a finished game woken
 * years later) migrates itself on activation.
 *
 * JSON columns are canonical-JSON text (`{ mode: "json" }`); every instant is
 * epoch milliseconds, matching the kernel's injected clock.
 */

import type { GameStatus, TransitionAction } from "@eigen/kernel";
import type { GameAccess, JsonObject, OutcomeEntry } from "@eigen/rules";
import { integer, primaryKey, sqliteTable, text } from "drizzle-orm/sqlite-core";
import type { CommandResult } from "../protocol.js";

/** The game row snapshot from lazy init + status + rng_seed. Exactly
 * one row, `id = 1`. The DO copies this from D1 once and owns `status` and
 * `rng_seed` from then on; D1's copy becomes the display read-model. */
export const meta = sqliteTable("meta", {
  id: integer("id").primaryKey(),
  gameId: text("game_id").notNull(),
  status: text("status").$type<GameStatus>().notNull(),
  access: text("access").$type<GameAccess>().notNull(),
  schemaVersion: integer("schema_version").notNull(),
  config: text("config", { mode: "json" }).$type<JsonObject>().notNull(),
  turnSeconds: integer("turn_seconds"),
  budgetSeconds: integer("budget_seconds"),
  incrementSeconds: integer("increment_seconds"),
  rated: integer("rated", { mode: "boolean" }).notNull(),
  ratingPool: text("rating_pool"),
  minPlayers: integer("min_players").notNull(),
  maxPlayers: integer("max_players").notNull(),
  createdBy: text("created_by"),
  /** Generated by the start command (`randomSeed()`); null in the lobby. */
  rngSeed: text("rng_seed"),
});

/** Seats. Both ids null ⇒ account purged mid-game (plays on as "Deleted
 * User", can never act). */
export const roster = sqliteTable("roster", {
  playerIndex: integer("player_index").primaryKey(),
  userId: text("user_id"),
  botId: text("bot_id"),
  type: text("type").$type<"human" | "bot">().notNull(),
});

/** One row per version — the single-row transition shape, and it is
 * **append-only immutable**: no transition row is ever updated after commit,
 * which is what makes this table the game's permanent history verbatim.
 * The engine-owned envelope is the row's typed columns; `state` is the
 * game's opaque payload, parsed through the version's schema before any
 * hook sees it. Serves live gap recovery and post-finish replay
 * (re-projected via `computeObservation`). */
export const transitions = sqliteTable("transitions", {
  version: integer("version").primaryKey(),
  state: text("state", { mode: "json" }).$type<JsonObject>().notNull(),
  /** The action that produced this transition; null for start (v0). */
  action: text("action", { mode: "json" }).$type<TransitionAction | null>(),
  pending: text("pending", { mode: "json" }).$type<number[]>().notNull(),
  /** The true client-facing deadline; the alarm arms at deadline + grace. */
  deadline: integer("deadline"),
  playerTimes: text("player_times", { mode: "json" }).$type<number[] | null>(),
  turnStartedAt: integer("turn_started_at"),
});

/** Per-seat projected frames, identified seats only — LIVE-ONLY: serves
 * socket gap recovery and the same-view compare, then the finish
 * compaction empties the whole table (replay re-projects instead).
 * A separate table so compaction never touches `transitions`. */
export const frames = sqliteTable(
  "frames",
  {
    version: integer("version").notNull(),
    playerIndex: integer("player_index").notNull(),
    /** The seat's `ObservationSlice`, flattened. */
    data: text("data", { mode: "json" }).$type<JsonObject>().notNull(),
    pendingPlayers: text("pending_players", { mode: "json" }).$type<number[]>().notNull(),
  },
  (t) => [primaryKey({ columns: [t.version, t.playerIndex] })],
);

/** `commandId → response` dedupe: a duplicate replays the stored
 * response instead of double-applying. Deleted by the finish compaction. */
export const commands = sqliteTable("commands", {
  commandId: text("command_id").primaryKey(),
  response: text("response", { mode: "json" }).$type<CommandResult>().notNull(),
  createdAt: integer("created_at").notNull(),
});

/** What the D1 apply needs, written atomically with the finish and
 * cleared only AFTER the apply succeeds — a surviving row is the recovery
 * signal for the gated admin re-poke. */
export const outbox = sqliteTable("outbox", {
  finishId: text("finish_id").primaryKey(),
  outcomes: text("outcomes", { mode: "json" }).$type<OutcomeEntry[]>().notNull(),
  createdAt: integer("created_at").notNull(),
});
