/**
 * The game DO's SQLite schema: one database per game,
 * live *and* finished: after the finish compaction this IS the game's
 * permanent history, field-for-field the future cold-tier blob.
 *
 * Applied by the drizzle `durable-sqlite` migrator inside the DO's
 * `blockConcurrencyWhile` lazy init; the generated `migrations.js` bundle
 * compiles into the worker, so every DO (including a finished game woken
 * years later) migrates itself on activation.
 *
 * JSON columns are canonical-JSON text (`{ mode: "json" }`); every instant is
 * epoch milliseconds, matching the kernel's injected clock.
 */

import type { GameStatus, TransitionAction } from "@eigeninteractive/kernel";
import type { GameAccess, JsonObject, OutcomeEntry } from "@eigeninteractive/rules";
import { integer, primaryKey, sqliteTable, text } from "drizzle-orm/sqlite-core";
import type { CommandResult } from "../protocol.js";

/** The game row snapshot from lazy init + status + rng_seed. Exactly
 * one row, `id = 1`. The DO copies this from D1 once and owns `status` and
 * `rng_seed` from then on; D1's copy becomes the display read-model. */
export const meta = sqliteTable("meta", {
  id: integer().primaryKey(),
  gameId: text().notNull(),
  status: text().$type<GameStatus>().notNull(),
  access: text().$type<GameAccess>().notNull(),
  schemaVersion: integer().notNull(),
  config: text({ mode: "json" }).$type<JsonObject>().notNull(),
  turnSeconds: integer(),
  budgetSeconds: integer(),
  incrementSeconds: integer(),
  rated: integer({ mode: "boolean" }).notNull(),
  ratingPool: text(),
  minPlayers: integer().notNull(),
  maxPlayers: integer().notNull(),
  createdBy: text(),
  /** Generated by the start command (`randomSeed()`); null in the lobby. */
  rngSeed: text(),
  /** Copied from D1 so a session snapshot can carry it: the waiting room needs
   * the invite code, and the DO is the only thing a game screen talks to. */
  shortCode: text().notNull(),
  /** The final per-seat results, written with the finish and RETAINED, unlike
   * the `outbox` row that the compaction drains.
   *
   * Retained because a cold open of a finished game has to be answerable from
   * the DO alone: outcomes are kernel output rather than game state, so they are
   * in no transition row, and the live finishing frame that carried them is long
   * gone by then. Null until the game finishes. */
  outcomes: text({ mode: "json" }).$type<OutcomeEntry[] | null>(),
  /** Monotonic session counter, incremented by EVERY commit, lobby or state.
   *
   * It totally orders {@link SessionSnapshot}s, which `version` cannot: a lobby
   * change has no version, so two roster snapshots and a lobby command's
   * response would otherwise be mutually unorderable. A client applies a
   * snapshot only when its `seq` exceeds the one it holds, which makes a
   * command response racing its own socket push, a duplicate delivery, and a
   * reconnect that missed nothing all resolve by comparing one integer.
   *
   * Reset to 0 by the abort teardown, which drops all storage. Sound because
   * abort is terminal and terminal statuses are absorbing, so the client's rule
   * accepts a terminal snapshot whatever its `seq`. */
  seq: integer().notNull(),
});

/** Seats. Both ids null ⇒ account purged mid-game (plays on as "Deleted
 * User", can never act). */
export const roster = sqliteTable("roster", {
  playerIndex: integer().primaryKey(),
  userId: text(),
  botId: text(),
  type: text().$type<"human" | "bot">().notNull(),
});

/** One row per version: the single-row transition shape, and it is
 * **append-only immutable**: no transition row is ever updated after commit,
 * which is what makes this table the game's permanent history verbatim.
 * The engine-owned envelope is the row's typed columns; `state` is the
 * game's opaque payload, parsed through the version's schema before any
 * hook sees it. Serves live gap recovery and post-finish replay
 * (re-projected via `computeObservation`). */
export const transitions = sqliteTable("transitions", {
  version: integer().primaryKey(),
  state: text({ mode: "json" }).$type<JsonObject>().notNull(),
  /** The action that produced this transition; null for start (v0). */
  action: text({ mode: "json" }).$type<TransitionAction | null>(),
  pending: text({ mode: "json" }).$type<number[]>().notNull(),
  /** The true client-facing deadline; the alarm arms at deadline + grace. */
  deadline: integer(),
  playerTimes: text({ mode: "json" }).$type<number[] | null>(),
  turnStartedAt: integer(),
});

/** Per-seat projected frames, identified seats only. LIVE-ONLY: serves
 * socket gap recovery and the same-view compare, then the finish
 * compaction empties the whole table (replay re-projects instead).
 * A separate table so compaction never touches `transitions`. */
export const frames = sqliteTable(
  "frames",
  {
    version: integer().notNull(),
    playerIndex: integer().notNull(),
    /** The seat's `ObservationSlice`, flattened. */
    data: text({ mode: "json" }).$type<JsonObject>().notNull(),
    pendingPlayers: text({ mode: "json" }).$type<number[]>().notNull(),
  },
  (t) => [primaryKey({ columns: [t.version, t.playerIndex] })],
);

/** `commandId → response` dedupe: a duplicate replays the stored
 * response instead of double-applying. Deleted by the finish compaction. */
export const commands = sqliteTable("commands", {
  commandId: text().primaryKey(),
  response: text({ mode: "json" }).$type<CommandResult>().notNull(),
  createdAt: integer().notNull(),
});

/** What the D1 apply needs, written atomically with the finish and
 * cleared only AFTER the apply succeeds; a surviving row is the recovery
 * signal for the gated admin re-poke. */
export const outbox = sqliteTable("outbox", {
  finishId: text().primaryKey(),
  outcomes: text({ mode: "json" }).$type<OutcomeEntry[]>().notNull(),
  createdAt: integer().notNull(),
});
